### ISSUE TITLE
Incorrect Setting of LOWER_BOUND in Product Price in BMECatWriter.cs

### ISSUE THREAD

**Issue by meinereina** [stephanstapel/BMECat.net#3]
I've identified a potential issue in the BMECatWriter.cs file where the LOWER_BOUND value for the product price is being incorrectly set. It seems that instead of setting the lower bound of the price, the tax value is being used.

## Location:
File: BMECatWriter.cs:152

The code currently sets the LOWER_BOUND to the tax value:

```csharp
Writer.WriteElementString("LOWER_BOUND", price.Tax.ToString());
```
The LOWER_BOUND should be set to the actual lower bound value of the price:

```csharp
Writer.WriteElementString("LOWER_BOUND", price.LowerBound.ToString());
```

**Comment by stephanstapel** [comment]
Yes, that looks like a bug. Can you issue a pull request?

**Comment by meinereina** [comment]
I don't have permissions to create an new banch or i don't know how github works. I host all my projects at gitlab ;)

**Comment by stephanstapel** [comment]
You can just fork the project, make the changes in your fork and then issue a pull request.

**Comment by meinereina** [comment]
job done

**Comment by stephanstapel** [comment]
fixed by https://github.com/stephanstapel/BMECat.net/pull/4.
Thanks!
